module gaussian_mod
    use, intrinsic :: ieee_arithmetic, only : ieee_value, ieee_quiet_nan
    use precision_mod
    use parameter_mod, only : SimulationParameters
    use network_mod, only : generate_fcnn
    use langevin_mod, only : construct_Q
    use theory_mod, only : solve_fixed_point_nonlinear, solve_lyapunov_triangular_blocked, &
        analytic_result, compute_energetics_theory, compute_lyapunov_residual
    use energetics_mod, only : aggregate_layer_energetics
    use output_mod, only : write_node_layers, write_fcnn_parameters
    implicit none
    private
    public :: run_gaussian_ensemble
contains
    subroutine run_gaussian_ensemble(param, sizes, means, stds, layers, r, noise, bias, adj, w, directory)
        type(SimulationParameters), intent(in) :: param
        integer, intent(in) :: sizes(:), layers(:)
        real(dp), intent(in) :: means(:), stds(:), r(:), noise(:,:), bias(:)
        logical, allocatable, intent(inout) :: adj(:,:)
        real(dp), allocatable, intent(inout) :: w(:,:)
        character(len=*), intent(in) :: directory
        real(dp), allocatable :: q(:,:), k(:,:), alpha(:,:), fixed(:)
        real(dp), allocatable :: heat(:), work(:), internal(:), entropy(:)
        real(dp), allocatable :: lh(:), lw(:), lu(:), le(:), norms(:)
        integer, allocatable :: counts(:)
        integer :: sample, ell, i, total_unit, layer_unit, ios, n_stable
        real(dp) :: max_real, tol, residual, missing, total
        character(len=8) :: status

        allocate(k(param%N,param%N), fixed(param%N), norms(size(sizes)))
        missing = ieee_value(0.0_dp, ieee_quiet_nan)
        call write_node_layers(directory//"/node_layers.csv", layers)
        open(newunit=total_unit, file=directory//"/gaussian_trials.csv", status="replace", iostat=ios)
        if (ios /= 0) error stop "Cannot open Gaussian trials output"
        open(newunit=layer_unit, file=directory//"/gaussian_layer_energetics.csv", status="replace", iostat=ios)
        if (ios /= 0) error stop "Cannot open Gaussian layer output"
        call write_fcnn_parameters( &
            directory//"/gaussian_parameters.csv", sizes, means, stds, &
            r, noise, param%seed, param%n__samples, param%coupling_type)
        write(total_unit,'(A)') "id,stability,max_real_part,EPR_total,weight_norm_sq,lyapunov_residual"
        write(layer_unit,'(A)') "id,Layer,node_count,HR_total,EPR_total,WR_total,UR_total,weight_norm_sq"
        n_stable=0
        do sample=1,param%n__samples
            ! The first draw was generated by main. Continue the RNG stream;
            ! r, noise, bias and layer assignments remain fixed across samples.
            if (sample > 1) call generate_fcnn(param,size(sizes)-2,sizes,means,stds,adj,w)
            select case(trim(param%coupling_type))
            case("LINEAR","DIFFUSIVE")
                call construct_Q(r,w,param%coupling_type,q)
            case("TANH","TANH_INPUT")
                call solve_fixed_point_nonlinear(r,w,bias,param%coupling_type,fixed,1.0e-10_dp,100)
                call construct_Q(r,w,param%coupling_type,q,fixed,bias)
            case default
                error stop "Unsupported Gaussian coupling type"
            end select
            max_real=maxval([(q(i,i),i=1,param%N)])
            tol=100*epsilon(1.0_dp)*max(1.0_dp,maxval(abs(q)))
            norms=0
            do i=1,param%N
                norms(layers(i))=norms(layers(i))+sum(w(i,:)**2)
            end do
            total=missing
            residual=missing
            status="stable"
            if (max_real > tol) then
                status="unstable"
            else if (max_real >= -tol) then
                status="marginal"
            else
                call solve_lyapunov_triangular_blocked(q,-noise,k,max_real,.false.,.true.)
                call analytic_result(q,noise,k,alpha,.false.,.true.)
                call compute_energetics_theory(q,noise,alpha,heat,work,internal,entropy)
                call aggregate_layer_energetics(layers,heat,work,internal,entropy,counts,lh,lw,lu,le)
                total=sum(entropy)
                n_stable=n_stable+1
                if (param%verify_lyapunov) &
                    call compute_lyapunov_residual(q,k,noise,.false.,.true.,residual)
            end if
            write(total_unit,'(*(G0,:,","))') sample,trim(status),max_real,total,sum(norms),residual
            do ell=1,size(sizes)
                if (status == "stable") then
                    write(layer_unit,'(*(G0,:,","))') sample,ell,counts(ell),lh(ell),le(ell), &
                        lw(ell),lu(ell),norms(ell)
                else
                    write(layer_unit,'(*(G0,:,","))') sample,ell,sizes(ell),missing,missing, &
                        missing,missing,norms(ell)
                end if
            end do
            if (mod(sample,max(1,param%n__samples/10)) == 0) &
                print *, "Gaussian samples completed:",sample,"/",param%n__samples
        end do
        close(total_unit)
        close(layer_unit)
        print *, "Gaussian stable samples:",n_stable,"/",param%n__samples
    end subroutine run_gaussian_ensemble
end module gaussian_mod
